package com.sih26003.smritisetu.data.local.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import java.util.UUID

/**
 * Stores local PIN authentication hashes for Caregivers and Doctors.
 * Patients DO NOT use PINs.
 */
@Entity(tableName = "users")
data class UserEntity(
    @PrimaryKey val id: String = UUID.randomUUID().toString(),
    val role: String, // "CAREGIVER" or "DOCTOR"
    val pinHash: String, // SHA-256 hash of local PIN
    val name: String,
    val phoneHash: String = "",
    val createdAt: Long = System.currentTimeMillis()
)

/**
 * Patient profiles. Source of truth is Room local database.
 * No internet required to view, create, or select.
 */
@Entity(
    tableName = "patients",
    indices = [Index(value = ["pseudonymCode"], unique = true)]
)
data class PatientEntity(
    @PrimaryKey val id: String = UUID.randomUUID().toString(),
    val pseudonymCode: String, // E.g., "AS-KAM-0042"
    val birthYear: Int,
    val gender: String, // "M", "F", "O"
    val primaryLanguage: String = "as", // "as", "mn", "br", "hi", "en"
    val cognitiveStage: String = "MCI", // "MCI", "Early Dementia", "Healthy Wellness"
    val photoPath: String? = null, // Path in app-private storage
    val linkCode: String? = null, // 6-digit link code for separate device mode
    val isSynced: Boolean = false,
    val createdAt: Long = System.currentTimeMillis()
)

/**
 * Family members and personal relationships for Family Trivia game.
 * Stored locally in app-private storage.
 */
@Entity(
    tableName = "relationships",
    foreignKeys = [
        ForeignKey(
            entity = PatientEntity::class,
            parentColumns = ["id"],
            childColumns = ["patientId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("patientId")]
)
data class RelationshipEntity(
    @PrimaryKey val id: String = UUID.randomUUID().toString(),
    val patientId: String,
    val name: String,
    val relationshipType: String, // "SPOUSE", "SON", "DAUGHTER", "GRANDSON", "GRANDDAUGHTER", "FRIEND"
    val photoPath: String? = null, // Private file storage
    val voiceClipPath: String? = null, // Private audio file
    val isSynced: Boolean = false
)

/**
 * Complete game session metrics. Evaluates performance, NOT dementia diagnosis.
 */
@Entity(
    tableName = "game_sessions",
    foreignKeys = [
        ForeignKey(
            entity = PatientEntity::class,
            parentColumns = ["id"],
            childColumns = ["patientId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("patientId"), Index("gameId")]
)
data class GameSessionEntity(
    @PrimaryKey val id: String = UUID.randomUUID().toString(),
    val patientId: String,
    val gameId: String, // "FAMILY_TRIVIA", "VOICE_CUE_CARD", "SEQUENCING", "CATEGORISATION", "VILLAGE_MARKET", "PATTERN_RECOGNITION"
    val difficultyLevel: Int, // 1 to 5
    val durationMs: Long,
    val accuracy: Float, // 0.0f to 1.0f
    val errors: Int,
    val reactionTimeMs: Long,
    val hesitationCount: Int,
    val adaptationDecision: Int, // Recommended next difficulty (1 to 5)
    val completed: Boolean,
    val timestamp: Long = System.currentTimeMillis(),
    val isSynced: Boolean = false
)

/**
 * Offline reminders for Medicine, Hydration, Activity, and Appointments.
 */
@Entity(
    tableName = "reminders",
    foreignKeys = [
        ForeignKey(
            entity = PatientEntity::class,
            parentColumns = ["id"],
            childColumns = ["patientId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("patientId")]
)
data class ReminderEntity(
    @PrimaryKey val id: String = UUID.randomUUID().toString(),
    val patientId: String,
    val title: String,
    val reminderType: String, // "MEDICINE", "HYDRATION", "EXERCISE", "APPOINTMENT"
    val hour: Int, // 0 to 23
    val minute: Int, // 0 to 59
    val voicePromptKey: String? = null,
    val isEnabled: Boolean = true,
    val isSynced: Boolean = false
)

/**
 * 6-digit Doctor access approvals.
 */
@Entity(
    tableName = "doctor_access",
    foreignKeys = [
        ForeignKey(
            entity = PatientEntity::class,
            parentColumns = ["id"],
            childColumns = ["patientId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("patientId")]
)
data class DoctorAccessEntity(
    @PrimaryKey val id: String = UUID.randomUUID().toString(),
    val patientId: String,
    val doctorAccessCode: String, // 6-digit code generated by caregiver
    val doctorName: String = "",
    val approvedAt: Long = System.currentTimeMillis(),
    val isRevoked: Boolean = false
)

/**
 * Durable offline sync queue for Firebase opportunistic messenger replication.
 */
@Entity(tableName = "sync_queue")
data class SyncQueueEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val tableName: String,
    val recordId: String,
    val operation: String, // "INSERT", "UPDATE", "DELETE"
    val payloadJson: String,
    val timestamp: Long = System.currentTimeMillis(),
    val retryCount: Int = 0,
    val status: String = "PENDING" // "PENDING", "SYNCED", "FAILED"
)

/**
 * Caregiver daily observational notes and incident logs. Persisted in Room SQLite.
 */
@Entity(
    tableName = "care_logs",
    foreignKeys = [
        ForeignKey(
            entity = PatientEntity::class,
            parentColumns = ["id"],
            childColumns = ["patientId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("patientId")]
)
data class CareLogEntity(
    @PrimaryKey val id: String = UUID.randomUUID().toString(),
    val patientId: String,
    val authorRole: String = "CAREGIVER",
    val category: String, // "MEDICINE", "FALL", "APPETITE", "SLEEP", "CONFUSION", "GENERAL"
    val severity: String, // "NORMAL", "WATCH", "PRIORITY", "URGENT"
    val notes: String,
    val timestamp: Long = System.currentTimeMillis(),
    val isSynced: Boolean = false
)
